---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: podinfo-dev
  namespace: dev
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:v*
spec:
  releaseName: podinfo-dev
  chart:
    git: git@github.com:extremeFunk/flux_cd
    path: charts/podinfo
    ref: master
  values:
    image:
      repository: us:gcr:io/linen-cubist-267010/echo
      tag: v1.2
    replicaCount: 2
    hpa:
      enabled: false